name: Production CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.14.1'

      - name: Install Yarn (Corepack)
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Install Dependencies
        run: yarn install --immutable
        env:
          # Note: We need this because node 24 is technically unsupported by some packages
          YARN_IGNORE_ENGINES: 1

      - name: Lint (ESLint)
        run: yarn nx lint travel-admin

      - name: Unit Tests (Jest)
        run: yarn nx test travel-admin

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRAVEL_DASHBOARD_F98A3 }}'
          channelId: live
          projectId: travel-dashboard-f98a3
          build_command: 'yarn nx build travel-admin --configuration=production'

      - name: Deploy Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRAVEL_DASHBOARD_F98A3 }}'
